---
name: jdtls
description: Java language server.
homepage: https://github.com/eclipse/eclipse.jdt.ls
licenses:
  - EPL-2.0
languages:
  - Java
categories:
  - LSP

source:
  # renovate:datasource=github-tags
  id: pkg:generic/eclipse/eclipse.jdt.ls@v1.43.0
  download:
    - target: [darwin_x64, darwin_arm64]
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
        lombok.jar: https://projectlombok.org/downloads/lombok.jar
      config: config_mac/

    - target: [linux_x64, linux_x86]
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
        lombok.jar: https://projectlombok.org/downloads/lombok.jar
      config: config_linux/

    - target: linux_arm64
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
        lombok.jar: https://projectlombok.org/downloads/lombok.jar
      config: config_linux_arm/

    - target: win
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
        lombok.jar: https://projectlombok.org/downloads/lombok.jar
      config: config_win/

schemas:
  lsp: vscode:https://raw.githubusercontent.com/redhat-developer/vscode-java/master/package.json

bin:
  jdtls: python:bin/jdtls

share:
  jdtls/lombok.jar: lombok.jar
  jdtls/plugins/: plugins/
  jdtls/plugins/org.eclipse.equinox.launcher.jar: plugins/org.eclipse.equinox.launcher.jar
  jdtls/config/: "{{source.download.config}}"
